[auth.external.google]
enabled = true
client_id = "184326335469-c3sf1998ffvff2890804jvh0n714qi70.apps.googleusercontent.com "
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false